services:
  postgres:
    image: postgres:16
    container_name: po_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: po_db
      POSTGRES_USER: po_user
      POSTGRES_PASSWORD: po_secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
